<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bdm_bootstrap_grid"
 *
 * Auto generated by Extension Builder 2016-10-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Flux Bootstrap Grid',
	'description' => 'Bootstrap Grid Extension build with Fluid TYPO3.',
	'category' => 'plugin',
	'author' => 'Benjamin Beck',
	'author_email' => 'beck@beck-digitale-medien.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);